public class InvocableCrewOnboardingMining {
    /*
    static List<Crew_Members__c> crewListM = new List<Crew_Members__c>();
    public static void orderMiningCrew(List<Crew_Members__c> crewList){
        
    //Create # of Mining Crew Members equal to input
        for(Integer i = 1; i <= numOfCrewM; i++){
            Crew_Members__c c = new Crew_Members__c();
            c.Name = 'Armstrong';
            c.Designation__c = 'Mining';
            c.Crew_List__c = squadAssignmentM;
            crewListM.add(c);
        }
        system.debug(crewListM);
		insert crewListM;
        List<Crew_Members__c> crewListM2 = [SELECT Name,Crew_Member_ID__c FROM Crew_Members__c 
                                            WHERE Name LIKE 'Armstron%'];
        for(Crew_Members__c c : crewListM2){
            c.Name = 'Armstrong ' + c.Crew_Member_ID__c;
        }
        update crewListM2;
    }
}*/
}